IF(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/.git)
  FIND_PACKAGE(Git)
  IF(GIT_FOUND)
    EXECUTE_PROCESS(COMMAND ${GIT_EXECUTABLE} rev-list -n 1 HEAD
      WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
      OUTPUT_VARIABLE VD_REVISION OUTPUT_STRIP_TRAILING_WHITESPACE)
    MESSAGE(STATUS "Void Revision ${VD_REVISION}")
  ELSE()
    MESSAGE(STATUS "No revision version support -- GIT not found")
  ENDIF()
ENDIF()
